### ISSUE TITLE
factorial(): second call to .next() should result in value 1

### ISSUE THREAD

**Issue by 6zz** [jasonly/breakfast-club#18]
factorial(0) = 1; factorial(1) = 1; for n > 1, factorial(n) = n * factorial(n-1);

so this test call here should expect 1 https://github.com/jasonly/breakfast-club/blob/master/test/04-generator-function.test.js#L18

**Comment by jasonly** [comment]
Ohh omg, you're right!

**Comment by jasonly** [comment]
Fixed it in https://github.com/jasonly/breakfast-club/commit/baa83b1903741a89a10e7e0b6acf6af36b685350
